// AUTOGENERATED FILE
// This file was generated from fable.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface FableDSLActionDict<T> extends BaseActionDict<T> {
  Fable?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode, arg4: TerminalNode) => T;
  FableContent?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Page?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode, arg3: TerminalNode, arg4: IterationNode, arg5: TerminalNode) => T;
  PageOption?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  PageContent?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Statement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  InitStatement?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  SetStatement?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  AddStatement?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  SubtractStatement?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Agent?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  TextAgent?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: IterationNode) => T;
  ButtonAgent?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: IterationNode, arg5: TerminalNode, arg6: IterationNode, arg7: TerminalNode) => T;
  ImageAgent?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: IterationNode) => T;
  VideoAgent?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  Event?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: IterationNode, arg3: TerminalNode) => T;
  EventType?: (this: NonterminalNode, arg0: TerminalNode) => T;
  MusicStatement?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  MusicOptions?: (this: NonterminalNode, arg0: IterationNode) => T;
  MusicOption?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  Action?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  GoToPageAction?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  PlaySoundAction?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PlaySoundWithVolume?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode) => T;
  PlaySoundWithoutVolume?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  StopMusicAction?: (this: NonterminalNode, arg0: TerminalNode) => T;
  StopSoundAction?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  MoveAction?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: NonterminalNode, arg6: IterationNode) => T;
  StopAnimationAction?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  WaitBlock?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode, arg4: TerminalNode) => T;
  TimerBlock?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: TerminalNode, arg4: IterationNode, arg5: TerminalNode) => T;
  Duration?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode) => T;
  TimeUnit?: (this: NonterminalNode, arg0: TerminalNode) => T;
  AnimateOption?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  AnimateParams?: (this: NonterminalNode, arg0: IterationNode) => T;
  AnimateParam?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  AgentRef?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  EasingOption?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  IfBlock?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode, arg4: TerminalNode) => T;
  ForBlock?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode, arg5: IterationNode, arg6: TerminalNode) => T;
  Position?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  Range?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Expression?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  LogicalExpr_or?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  LogicalExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AndExpr_and?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AndExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  CompExpr_equal?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CompExpr_not_equal?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CompExpr_less_equal?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CompExpr_greater_equal?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CompExpr_less?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CompExpr_greater?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  CompExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  AddExpr_plus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddExpr_minus?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  AddExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MulExpr_times?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExpr_div?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExpr_mod?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  MulExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  UnaryExpr_not?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExpr_neg?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  UnaryExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PrimaryExpr_paren?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  PrimaryExpr?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  RandomExpr?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  PickOneExpr?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  List?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  ListItems_multiple?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  ListItems_single?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  ListItems?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  InterpolatedString?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  innerString?: (this: NonterminalNode, arg0: IterationNode) => T;
  StringLiteral?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  NumberLiteral?: (this: NonterminalNode, arg0: IterationNode, arg1: IterationNode, arg2: IterationNode) => T;
  BooleanLiteral?: (this: NonterminalNode, arg0: TerminalNode) => T;
  identifier?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  space?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  comment?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
}

export interface FableDSLSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: FableDSLActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: FableDSLActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: FableDSLActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: FableDSLActionDict<T>): this;
}

export interface FableDSLGrammar extends Grammar {
  createSemantics(): FableDSLSemantics;
  extendSemantics(superSemantics: FableDSLSemantics): FableDSLSemantics;
}

declare const grammar: FableDSLGrammar;
export default grammar;

